
package com.client.jaxws.models;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CalculatorServiceImplService", targetNamespace = "http://services.web.com/", wsdlLocation = "http://localhost:8088/WS/CalculatorService?wsdl")
public class CalculatorServiceImplService
    extends Service
{

    private final static URL CALCULATORSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CALCULATORSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName CALCULATORSERVICEIMPLSERVICE_QNAME = new QName("http://services.web.com/", "CalculatorServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8088/WS/CalculatorService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCULATORSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        CALCULATORSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public CalculatorServiceImplService() {
        super(__getWsdlLocation(), CALCULATORSERVICEIMPLSERVICE_QNAME);
    }

    public CalculatorServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCULATORSERVICEIMPLSERVICE_QNAME, features);
    }

    public CalculatorServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, CALCULATORSERVICEIMPLSERVICE_QNAME);
    }

    public CalculatorServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCULATORSERVICEIMPLSERVICE_QNAME, features);
    }

    public CalculatorServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculatorServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CalculatorService
     */
    @WebEndpoint(name = "CalculatorServiceImplPort")
    public CalculatorService getCalculatorServiceImplPort() {
        return super.getPort(new QName("http://services.web.com/", "CalculatorServiceImplPort"), CalculatorService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculatorService
     */
    @WebEndpoint(name = "CalculatorServiceImplPort")
    public CalculatorService getCalculatorServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.web.com/", "CalculatorServiceImplPort"), CalculatorService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCULATORSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw CALCULATORSERVICEIMPLSERVICE_EXCEPTION;
        }
        return CALCULATORSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
