
package com.client.jaxws.models;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculatorService", targetNamespace = "http://services.web.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculatorService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://services.web.com/", className = "Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://services.web.com/", className = "AddResponse")
    @Action(input = "http://services.web.com/CalculatorService/addRequest", output = "http://services.web.com/CalculatorService/addResponse")
    public int add(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "divide", targetNamespace = "http://services.web.com/", className = "Divide")
    @ResponseWrapper(localName = "divideResponse", targetNamespace = "http://services.web.com/", className = "DivideResponse")
    @Action(input = "http://services.web.com/CalculatorService/divideRequest", output = "http://services.web.com/CalculatorService/divideResponse")
    public int divide(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "subtract", targetNamespace = "http://services.web.com/", className = "Subtract")
    @ResponseWrapper(localName = "subtractResponse", targetNamespace = "http://services.web.com/", className = "SubtractResponse")
    @Action(input = "http://services.web.com/CalculatorService/subtractRequest", output = "http://services.web.com/CalculatorService/subtractResponse")
    public int subtract(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "multiply", targetNamespace = "http://services.web.com/", className = "Multiply")
    @ResponseWrapper(localName = "multiplyResponse", targetNamespace = "http://services.web.com/", className = "MultiplyResponse")
    @Action(input = "http://services.web.com/CalculatorService/multiplyRequest", output = "http://services.web.com/CalculatorService/multiplyResponse")
    public int multiply(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
